@extends('layouts.app')
@section('content')


<div class="faq-full-section">

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="process-head-wrap">
        <div class="our-company-head-wrap">
            <h1 class="txt-center">Privacy Policy</h1>
          </div>
        
        </div>
      </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <p class="paraf1 paraf-margin">Adamant International. ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Adamant International. This Privacy Policy applies to our website, www.adamantgems.com , and its associated subdomains (collectively, our "Service"). 
            By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service. 
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h3 class="paraf-margin">Definitions and key terms </h3>
            <p class="paraf1">
             <span class="privacy-color">Cookie:</span> a small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
            </p>

            <p class="paraf1">
             <span class="privacy-color">Company: </span>When this policy mentions “company”, “us” or “we”, it refers to Adamant International Private Limited of 81 Ward Place, Colombo, Sri Lanka that is responsible for your information under this Privacy Policy.
            </p>

            <p class="paraf1">
             <span class="privacy-color">Country: </span>Where Adamant International or the owners/founders of Adamant International are based, in this case is Sri Lanka. 
            </p>
            <p class="paraf1">
             <span class="privacy-color">Customer: </span>Refers to the company, organization or person that signs up to use the Adamant International Service to manage the relationships with your consumers or service users. 
            </p>
            <p class="paraf1">
             <span class="privacy-color">Device: </span>Any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Adamant International and use the services.  
            </p>
            <p class="paraf1">
             <span class="privacy-color">IP address: </span>Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.   
            </p>
            <p class="paraf1">
             <span class="privacy-color">Personnel: </span>Refers to those individuals who are employed by Adamant International or are under contract to perform a service on behalf of one of the parties.    
            </p>
            <p class="paraf1">
             <span class="privacy-color">Personal Data: </span>Any information that directly, indirectly, or in connection with other information allows for the identification or identifiability of a natural person.  
            </p>
            <p class="paraf1">
             <span class="privacy-color">Service: </span>Refers to the service provided by Adamant International as described in the relative terms (if available) and on this platform.   
            </p>
            <p class="paraf1">
             <span class="privacy-color">Third-party service: </span>Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.    
            </p>
            <p class="paraf1">
             <span class="privacy-color">Website:  </span>Adamant International’s site, which can be accessed via this URL: www.adamantgems.com.     
            </p>
            <p class="paraf1">
             <span class="privacy-color">You: </span>A person or entity that is registered with Adamant International to use the Services.      
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3 class="paraf-margin">Information automatically collected </h3>
            <p class="paraf1">
            There is some information like your Internet Protocol (IP) address and/or browser and device characteristics that is collected automatically when you visit our platform. This information may be used to connect your computer to the Internet. Other information collected automatically could be a login, e-mail address, password, computer and connection information such as browser plug-in types and versions and time zone setting, operating systems and platforms, the full Uniform Resource Locator (URL) clickstream to, through and from our Website that may include date and time; cookie number; parts of the site you viewed or searched for; and the phone number you used to call our Customer Services. We may also use browser data such as cookies, Flash cookies (also known as Flash Local Shared Objects) or similar data on certain parts of our Website for fraud prevention and other purposes. During your visits, we may use software tools such as JavaScript to measure and collect session information including page response times, download errors, length of visits to certain pages, page interaction information (such as scrolling, clicks, and mouse-overs), and methods used to browse away from the page. We may also collect technical information to help us identify your device for fraud prevention and diagnostic purposes. 
            </p>
            <p class="paraf1">
            We automatically collect certain information when you visit, use or navigate the platform. This information does not reveal your specific identity (like your name or contact information) but may include device and usage information, such as your IP address, browser and device characteristics, operating system, language preferences, referring URLs, device name, country, location, and other technical information. This information is primarily needed to maintain the security and operation of our website, and for our internal analytics and reporting purposes. 
            </p>

            
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h3 class="paraf-margin">How do we use the information we collect? </h3>
            <p class="paraf1">
            Any of the information we collect from you may be used in one of the following ways: 
            </p>
            <ul>
                <li class="paraf1">To persona class=""ze your experience (your information helps us to better respond to your individual needs) </li>
                <li class="paraf1">To improve our service (we continually strive to improve our service offerings based on the information and feedback we receive from you) </li>
                <li class="paraf1">To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs) </li>
                <li class="paraf1">To process transactions </li>
                <li class="paraf1">To administer a contest, promotion, survey or other site feature </li>
                <li class="paraf1">To send periodic emails if you choose to sign up for them (i.e. “newsletter”) </li>
            </ul>

            
        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            <h3 class="paraf-margin">Do we share the information we collect with third parties</h3>
            <p class="paraf1">
            We do not share any personal information with any third parties except as normally requested by delivery couriers such as air mail or FedEx in order to deliver your parcel.  
            </p>

            <p class="paraf1">
            We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners or application developers.  
            </p>
            <p class="paraf1">
            If your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, whether you have visited the service in a shared location, and type of device used to visit the service, in order to optimize the website’s speed or response time. 
            </p>
            <p class="paraf1">
            We may also disclose personal and non-personal information about you to government or law enforcement officials as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations.  
            </p>
            

            
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h3 class="paraf-margin">Where and when is information collected from customers and end users? </h3>
            <p class="paraf1">
            We will collect personal information that you submit to us when you make a purchase, but it is kept only in form of past invoices for local tax purposes.   
            </p>

            <p class="paraf1">
            Could my information be transferred to other countries? 
            </p>
            <p class="paraf1">
            We are incorporated in Sri Lanka. Information collected via our website, through direct interactions with you, or from use of our help services may be transferred from time to time to our personnel within or outside of Sri Lanka, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the trans- border transfer and hosting of such information. 
            </p>
           
            

            
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h3 class="paraf-margin">Is the information collected through our service secure? </h3>
            <p class="paraf1">
            We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. 
            </p>

            <p class="paraf1">
            Can I update or correct my information? 
            </p>
            <p class="paraf1">
            You can contact us in order to (1) update or correct your personally identifiable information, (2) change your preferences with respect to communications and other information you receive from us, or (3) delete the personally identifiable information maintained about you on our systems (subject to the following paragraph) at any time. Such updates, corrections, changes and deletions will have no effect on other non-personal information that we maintain for technical purposes, as outlined with this Privacy Policy prior to such update, correction, change or deletion. If you are an end user and wish to update, delete, or receive any information we have about you, you may do so by contacting the organization of which you are a customer. 
            </p>
           
            

            
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3 class="paraf-margin">Sale of Business </h3>
            <p class="paraf1">
            We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of us or any of its Corporate Affiliates (as defined herein), or that portion of us or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy. 
            </p>

           
           
            

            
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3 class="paraf-margin">How Long Do We Keep Your Information? </h3>
            <p class="paraf1">
            We keep your information only so long as we need it to provide service to you and fulfill the purposes described in this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we'll either remove it from our systems or depersonalize it so that we can't identify you.  
            </p>

           
           
            

            
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3 class="paraf-margin">How Do We Protect Your Information? </h3>
            <p class="paraf1">
            We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied information is transmitted via Secure Socket Layer (SSL) technology and then encrypted only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential.   
            </p>

           
           
            

            
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3 class="paraf-margin">Governing Law </h3>
            <p class="paraf1">
            The laws of Sri Lanka, excluding its conflicts of law rules, shall govern this Agreement and your use of our service. Your use of our service may also be subject to other local, state, national, or international laws.    
            </p>

           
           
            

            
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3 class="paraf-margin">Your Consent </h3>
            <p class="paraf1">
            By using our service, registering an account, or making a purchase, you consent to this Privacy Policy.     
            </p>

           
           
            

            
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3 class="paraf-margin">Links to Other Websites </h3>
            <p class="paraf1">
            This Privacy Policy applies only to the Services. The Services may occasionally contain clearly specified links to other websites not operated or controlled by Adamant International Private Limited. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the our Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.  
            </p>

           
           
            

            
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3 class="paraf-margin">Cookies</h3>
            <p class="paraf1">
            We use "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to personalize the Content that you see on our website. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place personally identifiable information in Cookies.   
            </p>

           
           
            

            
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3 class="paraf-margin">Kids' Privacy </h3>
            <p class="paraf1">
            We do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with personal data, please contact us.   
            </p>

           
           
            

            
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3 class="paraf-margin">Changes To Our Privacy Policy </h3>
            <p class="paraf1">
            If we decide to change our privacy policy, we will post those changes on this page, and/or update the Privacy Policy modification date below.    
            </p>

           
           
            

            
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3 class="paraf-margin">Third-Party Services </h3>
            <p class="paraf1">
            We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third-Party Services"). You acknowledge and agree that we shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. We do not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services. Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.     
            </p>
            <p class="paraf1">
            Updated 01 August 10:42, 2022     
            </p>

           
           
            

            
        </div>
    </div>


  </div>

  







</div>




@endsection

